# data228project

On December 31st 2019, the outbreak of coronavirus was reported to the WHO(World health organization), from Wuhan China. 